# Generated by Django 5.0.2 on 2024-02-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fasteignakaup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAERSLUNUMER', models.IntegerField()),
                ('EMNR', models.IntegerField()),
                ('SKJALANUMER', models.CharField(max_length=100)),
                ('FASTNUM', models.IntegerField()),
                ('HEIMILISFANG', models.CharField(max_length=100)),
                ('POSTNR', models.IntegerField()),
                ('HEINUM', models.IntegerField()),
                ('SVFN', models.IntegerField()),
                ('SVEITARFELAG', models.CharField(max_length=100)),
                ('UTGDAG', models.DateTimeField()),
                ('THINGLYSTDAGS', models.DateTimeField()),
                ('KAUPVERD', models.IntegerField()),
                ('FASTEIGNAMAT', models.IntegerField()),
                ('FASTEIGNAMAT_GILDANDI', models.CharField(max_length=100)),
                ('BRUNABOTAMAT_GILDANDI', models.CharField(max_length=100)),
                ('BYGGAR', models.CharField(max_length=100)),
                ('FEPILOG', models.CharField(max_length=100)),
                ('EINFLM', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LOD_FLM', models.CharField(max_length=100)),
                ('LOD_FLMEIN', models.CharField(max_length=100)),
                ('FJHERB', models.CharField(max_length=100)),
                ('TEGUND', models.CharField(max_length=100)),
                ('FULLBUID', models.IntegerField()),
                ('ONOTHAEFUR_SAMNINGUR', models.IntegerField()),
            ],
        ),
    ]
